from flask.ext.wtf import Form
from app import db
from models import User, LessonPlan
from wtforms import TextField, TextAreaField, DateField, SelectField
from wtforms.validators import Required, Email, EqualTo, Length, ValidationError, Optional


class LessonPlanForm(Form):
	title = TextField('title', validators = [Required()])
	projectedDate = DateField(format='%m %d %y')
	instructors = TextField('instructors', validators = [None])
	learningOutcome1 = TextField('outcome1', validators = [None])
	learningOutcome2 = TextField('outcome2', validators = [None])
	learningOutcome3 = TextField('outcome3', validators = [None])
	learningOutcome4 = TextField('outcome4', validators = [None])
	learningOutcome5 = TextField('outcome5', validators = [None])
	learningOutcome6 = TextField('outcome6', validators = [None])
	learningOutcome7 = TextField('outcome7', validators = [None])
	learningOutcome8 = TextField('outcome8', validators = [None])
	learningOutcome9 = TextField('outcome9', validators = [None])
	learningOutcome10 = TextField('outcome10', validators = [None])
	prep = TextAreaField('prep', validators = [None])
	materials = TextAreaField('materials', validators = [None])
	participantMaterials = TextAreaField('studentMaterials', validators = [None])
	time1 = TextField('time1', validators = [None])
	time2 = TextField('time2', validators = [None])
	time3 = TextField('time3', validators = [None])
	time4 = TextField('time4', validators = [None])
	time5 = TextField('time5', validators = [None])
	time6 = TextField('time6', validators = [None])
	time7 = TextField('time7', validators = [None])
	time8 = TextField('time8', validators = [None])
	time9 = TextField('time9', validators = [None])
	time10 = TextField('time10', validators = [None])
	activity1 = TextField('activity1', validators = [None])
	activity2 = TextField('activity2', validators = [None])
	activity3 = TextField('activity3', validators = [None])
	activity4 = TextField('activity4', validators = [None])
	activity5 = TextField('activity5', validators = [None])
	activity6 = TextField('activity6', validators = [None])
	activity7 = TextField('activity7', validators = [None])
	activity8 = TextField('activity8', validators = [None])
	activity9 = TextField('activity9', validators = [None])
	activity10 = TextField('activity10', validators = [None])
	activity1notes = TextAreaField('activity1', validators = [None])
	activity2notes = TextAreaField('activity2', validators = [None])
	activity3notes = TextAreaField('activity3', validators = [None])
	activity4notes = TextAreaField('activity4', validators = [None])
	activity5notes = TextAreaField('activity5', validators = [None])
	activity6notes = TextAreaField('activity6', validators = [None])
	activity7notes = TextAreaField('activity7', validators = [None])
	activity8notes = TextAreaField('activity8', validators = [None])
	activity9notes = TextAreaField('activity9', validators = [None])
	activity10notes = TextAreaField('activity10', validators = [None])
	trainernotes = TextAreaField('trainernotes', validators = [None])
